defaults:
  - temos_3dVista #temos or temos_transf or temos_feats
  - _self_

_target_: src.model.MonSTeR

lmd:
  recons: 1.0
  latent: 1.0e-5 #defaul 1.0e-5
  kl: 1.0e-5
  contrastive: 1.0 #default 0.1
  crop: 1.0 #weight for the Binary cross entropy of the scene decoder

lr: 1e-5
temperature: 0.1 
threshold_selfsim: 0.8 #0.8 #0.8 #0.8q
threshold_selfsim_metrics: 0.95 #0.95
two_level: false
no_single: false
#############################
baseline: false
# use_joint_encoder= if true use an encoder for text and scene combined 
# text as bridge is a variant of the vanilla, where everything is aligned to the text
bridge: 't' #t, m, s, all
ckpt_name: 'outputs/TMR_weights/last_weights' #TMR checkpoint
########OLD_HERE_ONLY_FOR_BACKWARD_COMPATIBILITY#################
# If you want to recostruct xyz-rotat
train_dl_len: 0
total_steps: 0
cross_mod_eval: 'mean'
#use Cube?
