defaults:
  - temos
  - _self_

_target_: src.model.TMR

lmd:
  recons: 1.0
  latent: 1.0e-5
  kl: 1.0e-5
  contrastive: 0.1

lr: 1e-4
temperature: 0.1
threshold_selfsim: 0.80
threshold_selfsim_metrics: 0.95
ckpt_name: 'outputs/TMR/models/tmr_humanise_guoh3dfeats/last_weights'
