trainer:
  _target_: pytorch_lightning.Trainer

  max_epochs: 140
  log_every_n_steps: 50
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  accelerator: gpu
  devices: 1 #DO NOT CHANGE this would drastically change the validation metrics recorded
  #gradient_clip_val: 1
  callbacks:
    # - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    #   filename: latest-{epoch}
    #   every_n_epochs: 1
    #   save_top_k: 1
    #   save_last: true
    # - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    #   filename: latest-{epoch}
    #   monitor: step
    #   mode: max
    #   every_n_epochs: 100
    #   save_top_k: -1 #All-pair-st2m/R05_epoch
    #   save_last: false
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      filename: best_st2m-{epoch}
      monitor: All/rank3/st2m
      mode: max
      every_n_epochs: 1
      save_top_k: 7
      save_last: true
    - _target_: src.callback.progress.ProgressLogger
      precision: 3
    - _target_: src.callback.tqdmbar.TQDMProgressBar

  logger:
      _target_: pytorch_lightning.loggers.wandb.WandbLogger
      save_dir: ${run_dir}
      name: "MonSTeR"
      project: "MonSTeR" 
      entity: "pinlab-sapienza"
      group: "NewSplit"
      tags : ["MonSTeR"]
